---
Name: security-headers
After: 'coreconfig'
---
Guttmann\SilverStripe\SecurityHeaderControllerExtension:
  headers:
    Content-Security-Policy: "default-src 'self';"
    Strict-Transport-Security: "max-age=31536000"
    Frame-Options: "deny"
    X-Content-Type-Options: "nosniff"
